const uris = {
    charts: "/charts",
    cart: "/cart",
    colorExcel: '/color',
    contact: "/contact",
    customRequest: "/custom-request",
    excel: '/excel',
    fieldCalculations: '/field-calculations',
    fieldMapper: "/field",
    fileLinks: '/file-links',
    home: "/",
    language: "/detect-language",
    logicSyntax: "/logic-syntax",
    metaData: "/meta-data",
    multiExcel: '/multi-excel',
    npxExcel: "/npx-excel",
    npxToJson: "/npx-json",
    permid: "/permid",
    pdfCompress: "/compress-pdf",
    pdfTable: "/pdf-table",
    products: "/products",
    profile: "/my-profile",
    validateLinks: '/validate-links',
}

export default uris